import React, {useState, useEffect, useRef} from "react";
import Link from 'next/link'

import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next.js DApps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="navbar bg-gray-700 ">
        <div className="navbar_nav">
          <div className="p-2 flex flex-row  justify-start">
            <button className="md:hidden rounded-lg focus:outline-none focus:shadow-none text-white">
              <svg width="20px" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                <path fill="currentColor" d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z" />
              </svg>
            </button>
            <Link href="/"><a className="text-xl md:text-2xl ml-5  md:ml-10  focus:outline-none focus:shadow-outline  text-white">
            NEXTDAPPS
            </a></Link>
          </div>
        </div>
      </nav>

      <main>
        <div className="container justify-center text-center mt-40">
        <h1 className="text-gray-700 text-2xl md:text-4xl  font-Poppins">
          NextJS DECENTRILIZED APPS
        </h1>

        <h1 className="text-gray-700 text-lg md:text-2xl  mt-10">
          Basic NextJS With TAILWINDS CSS
        </h1>
      </div>
    </main>

      <footer className="fixed bottom-0 w-full border text-center py-3 bg-gray-100">
        <p className="mx-auto">By Giant Defi 2022</p> 
      </footer>
    </div>
  )
}
