import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next DApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 style={{textAlign: 'center', marginTop: "10%"}}>
          NEXT.JS DECENTRILIZED APPS
        </h1>
      </main>

      <footer style={{textAlign: 'center', position : "absolute", bottom: 0, left : '50%', marginBottom: 10}}>
        By Giant Defi
      </footer>
    </div>
  )
}
